const data = {
    productItems: [
        { id: 1, desc: " ", loai: "Ghế mây đơn", name: "Ghế mây Franco Albini", gia: 1800000, giacu: 2200000, img: "/img/img_sp-01.png" ,mota:"Sản phẩm được làm bằng 100% chất liệu từ thiên nhiên, Sản phẩm nội thất mây chất lượng cao nhất trên thị trường. Độ bền cao, thời gian sử dụng lâu dài.Kỹ thuật giữ màu mây tự nhiên, không thêm tạp chất, hoá chất, hoàn toàn thân thiện với môi trường."},
        { id: 2, desc: " ", loai: "thùng đựng đồ", name: "Sọt mây Aloha Haha", gia: 800000, giacu: 800000, img: "/img/img_sp-02.png" ,mota:"Sản phẩm được làm bằng 100% chất liệu từ thiên nhiên, Sản phẩm nội thất mây chất lượng cao nhất trên thị trường. Độ bền cao, thời gian sử dụng lâu dài.Kỹ thuật giữ màu mây tự nhiên, không thêm tạp chất, hoá chất, hoàn toàn thân thiện với môi trường."},
        { id: 3, desc: " ", loai: "sofa", name: "Sofa Franco Albini", gia: 280000, giacu: 5900000, img: "/img/img_sp-03.png" ,mota:"Sản phẩm được làm bằng 100% chất liệu từ thiên nhiên, Sản phẩm nội thất mây chất lượng cao nhất trên thị trường. Độ bền cao, thời gian sử dụng lâu dài.Kỹ thuật giữ màu mây tự nhiên, không thêm tạp chất, hoá chất, hoàn toàn thân thiện với môi trường."},
        { id: 4, desc: " ", loai: "Ghế mây đơn", name: "Ghế mây Franco Albini", gia: 1800000, giacu: 2200000, img: "/img/img_sp-04.png" ,mota:"Sản phẩm được làm bằng 100% chất liệu từ thiên nhiên, Sản phẩm nội thất mây chất lượng cao nhất trên thị trường. Độ bền cao, thời gian sử dụng lâu dài.Kỹ thuật giữ màu mây tự nhiên, không thêm tạp chất, hoá chất, hoàn toàn thân thiện với môi trường."},
        { id: 5, desc: " ", loai: "vật dụng decor", name: "Cú mèo Franco Albini", gia: 650000, giacu: 650000, img: "/img/img_sp-05.png" ,mota:"Sản phẩm được làm bằng 100% chất liệu từ thiên nhiên, Sản phẩm nội thất mây chất lượng cao nhất trên thị trường. Độ bền cao, thời gian sử dụng lâu dài.Kỹ thuật giữ màu mây tự nhiên, không thêm tạp chất, hoá chất, hoàn toàn thân thiện với môi trường."},
        { id: 6, desc: " ", loai: "papasan", name: "PapasanPapasan Franco Albini", gia: 2400000, giacu: 4200000, img: "/img/img_sp-06.png" ,mota:"Sản phẩm được làm bằng 100% chất liệu từ thiên nhiên, Sản phẩm nội thất mây chất lượng cao nhất trên thị trường. Độ bền cao, thời gian sử dụng lâu dài.Kỹ thuật giữ màu mây tự nhiên, không thêm tạp chất, hoá chất, hoàn toàn thân thiện với môi trường."},
        { id: 7, desc: " ", loai: "Giường tủ", name: "Kệ mây Franco Albini", gia: 2400000, giacu: 4200000, img: "/img/img_sp-07.png" ,mota:"Sản phẩm được làm bằng 100% chất liệu từ thiên nhiên, Sản phẩm nội thất mây chất lượng cao nhất trên thị trường. Độ bền cao, thời gian sử dụng lâu dài.Kỹ thuật giữ màu mây tự nhiên, không thêm tạp chất, hoá chất, hoàn toàn thân thiện với môi trường."},
        { id: 8, desc: " ", loai: "sofa", name: "Bộ Sofa Franco Albini", gia: 18800000, giacu: 22200000, img: "/img/img_sp-08.png" ,mota:"Sản phẩm được làm bằng 100% chất liệu từ thiên nhiên, Sản phẩm nội thất mây chất lượng cao nhất trên thị trường. Độ bền cao, thời gian sử dụng lâu dài.Kỹ thuật giữ màu mây tự nhiên, không thêm tạp chất, hoá chất, hoàn toàn thân thiện với môi trường."},
    ],
};
export default data;